// Mock hospital dataset for Medical Migration Map
// Coordinates are spread around Bengaluru, India for demo purposes

export const HOSPITALS = [
  {
    id: 1,
    name: "Manipal Hospital (Whitefield)",
    lat: 12.9698,
    lng: 77.7500,
    rating: 4.7,
    distance: 1.2,
    ayushmanBharat: true,
    insuranceProviders: ["Star Health", "HDFC ERGO", "National Insurance", "New India"],
    pricing: { general: 1200, semiPrivate: 2800, private: 5500 },
    emergency: true,
    specialties: ["Cardiology", "Orthopedics", "Neurology", "Oncology"],
    departments: ["Cardiology", "Orthopedics", "Neurology", "Oncology", "Gastroenterology", "Radiology"],
    specialists: [
      { name: "Dr. Ramesh Nair", dept: "Cardiology", exp: "18 yrs" },
      { name: "Dr. Sunita Rao", dept: "Orthopedics", exp: "14 yrs" },
      { name: "Dr. Vikram Bhat", dept: "Neurology", exp: "22 yrs" },
      { name: "Dr. Priya Shetty", dept: "Oncology", exp: "10 yrs" },
    ],
    bedAvailability: { general: 42, semiPrivate: 12, private: 6, icu: 4 },
    estimatedTreatmentCost: { bypass: "2.5L–4L", kneeReplacement: "1.8L–2.8L", appendectomy: "60K–1L" },
    description: "Tertiary care hospital with advanced cardiac and neuro sciences.",
  },
  {
    id: 2,
    name: "Fortis Hospital (Bannerghatta)",
    lat: 12.8913,
    lng: 77.5970,
    rating: 4.5,
    distance: 3.8,
    ayushmanBharat: false,
    insuranceProviders: ["Star Health", "Bajaj Allianz", "ICICI Lombard"],
    pricing: { general: 2000, semiPrivate: 4500, private: 9000 },
    emergency: true,
    specialties: ["Cardiology", "Oncology", "Transplant", "Pediatrics"],
    departments: ["Cardiology", "Oncology", "Transplant", "Pediatrics", "Gynecology", "Dermatology"],
    specialists: [
      { name: "Dr. Anil Mehta", dept: "Cardiology", exp: "25 yrs" },
      { name: "Dr. Kavitha Reddy", dept: "Oncology", exp: "16 yrs" },
      { name: "Dr. Suresh Kumara", dept: "Transplant", exp: "20 yrs" },
    ],
    bedAvailability: { general: 28, semiPrivate: 18, private: 14, icu: 8 },
    estimatedTreatmentCost: { bypass: "4L–6L", kneeReplacement: "2.5L–4L", appendectomy: "80K–1.2L" },
    description: "Premium multispeciality with world-class transplant services.",
  },
  {
    id: 3,
    name: "Victoria Government Hospital",
    lat: 12.9719,
    lng: 77.5771,
    rating: 3.9,
    distance: 5.1,
    ayushmanBharat: true,
    insuranceProviders: ["National Insurance", "New India", "ESI"],
    pricing: { general: 150, semiPrivate: 500, private: 1200 },
    emergency: true,
    specialties: ["General Medicine", "Surgery", "Gynecology", "Orthopedics"],
    departments: ["General Medicine", "Surgery", "Gynecology", "Orthopedics", "ENT", "Ophthalmology"],
    specialists: [
      { name: "Dr. M. Krishnappa", dept: "General Medicine", exp: "30 yrs" },
      { name: "Dr. Usha Rani", dept: "Gynecology", exp: "22 yrs" },
    ],
    bedAvailability: { general: 120, semiPrivate: 30, private: 10, icu: 12 },
    estimatedTreatmentCost: { bypass: "Govt. Subsidised", kneeReplacement: "Govt. Subsidised", appendectomy: "Free under Ayushman" },
    description: "Major government hospital offering subsidised treatment under Ayushman Bharat.",
  },
  {
    id: 4,
    name: "Narayana Health City",
    lat: 12.8916,
    lng: 77.6412,
    rating: 4.6,
    distance: 6.7,
    ayushmanBharat: true,
    insuranceProviders: ["Star Health", "HDFC ERGO", "Bajaj Allianz", "National Insurance", "United India"],
    pricing: { general: 900, semiPrivate: 2000, private: 4000 },
    emergency: true,
    specialties: ["Cardiac Surgery", "Neurosurgery", "Orthopedics", "Oncology"],
    departments: ["Cardiac Surgery", "Neurosurgery", "Orthopedics", "Oncology", "Nephrology", "Urology"],
    specialists: [
      { name: "Dr. Devi Prasad Shetty", dept: "Cardiac Surgery", exp: "35 yrs" },
      { name: "Dr. Anitha Kumar", dept: "Neurosurgery", exp: "18 yrs" },
      { name: "Dr. Raj Gopal", dept: "Nephrology", exp: "15 yrs" },
    ],
    bedAvailability: { general: 80, semiPrivate: 40, private: 25, icu: 20 },
    estimatedTreatmentCost: { bypass: "1.8L–3L", kneeReplacement: "1.5L–2.2L", appendectomy: "45K–75K" },
    description: "World-renowned for affordable cardiac care at highest quality.",
  },
  {
    id: 5,
    name: "Apollo Hospital (Jayanagar)",
    lat: 12.9255,
    lng: 77.5832,
    rating: 4.4,
    distance: 8.3,
    ayushmanBharat: false,
    insuranceProviders: ["Star Health", "HDFC ERGO", "ICICI Lombard", "Bajaj Allianz", "Tata AIG"],
    pricing: { general: 1800, semiPrivate: 3800, private: 8000 },
    emergency: true,
    specialties: ["Oncology", "Orthopedics", "Neurology", "Gastroenterology"],
    departments: ["Oncology", "Orthopedics", "Neurology", "Gastroenterology", "Endocrinology", "Pulmonology"],
    specialists: [
      { name: "Dr. Shyam Prasad", dept: "Oncology", exp: "20 yrs" },
      { name: "Dr. Meenakshi Iyer", dept: "Neurology", exp: "17 yrs" },
      { name: "Dr. Rohit Verma", dept: "Gastroenterology", exp: "12 yrs" },
    ],
    bedAvailability: { general: 35, semiPrivate: 22, private: 18, icu: 10 },
    estimatedTreatmentCost: { bypass: "3.5L–5.5L", kneeReplacement: "2.2L–3.5L", appendectomy: "70K–1.1L" },
    description: "Apollo's flagship with comprehensive cancer and neuro services.",
  },
  {
    id: 6,
    name: "BGS Global Hospital",
    lat: 12.9352,
    lng: 77.5160,
    rating: 4.3,
    distance: 9.6,
    ayushmanBharat: true,
    insuranceProviders: ["Star Health", "National Insurance", "New India"],
    pricing: { general: 800, semiPrivate: 1800, private: 3500 },
    emergency: true,
    specialties: ["Cardiology", "Nephrology", "Transplant", "Orthopedics"],
    departments: ["Cardiology", "Nephrology", "Transplant", "Orthopedics", "Pulmonology"],
    specialists: [
      { name: "Dr. Nataraj B.", dept: "Nephrology", exp: "21 yrs" },
      { name: "Dr. Sathish Kumar", dept: "Cardiology", exp: "16 yrs" },
    ],
    bedAvailability: { general: 55, semiPrivate: 20, private: 12, icu: 9 },
    estimatedTreatmentCost: { bypass: "2L–3.5L", kneeReplacement: "1.6L–2.4L", appendectomy: "50K–85K" },
    description: "Known for transplant services and Ayushman Bharat empanelment.",
  },
  {
    id: 7,
    name: "Sparsh Hospital (Yeshwanthpur)",
    lat: 13.0196,
    lng: 77.5497,
    rating: 4.2,
    distance: 11.4,
    ayushmanBharat: false,
    insuranceProviders: ["HDFC ERGO", "Bajaj Allianz", "ICICI Lombard"],
    pricing: { general: 1500, semiPrivate: 3000, private: 6000 },
    emergency: false,
    specialties: ["Orthopedics", "Spine Surgery", "Sports Medicine"],
    departments: ["Orthopedics", "Spine Surgery", "Sports Medicine", "Physiotherapy", "Rheumatology"],
    specialists: [
      { name: "Dr. Hanumanthaiah", dept: "Spine Surgery", exp: "19 yrs" },
      { name: "Dr. Pradeep Chandran", dept: "Sports Medicine", exp: "11 yrs" },
    ],
    bedAvailability: { general: 20, semiPrivate: 15, private: 10, icu: 3 },
    estimatedTreatmentCost: { bypass: "N/A", kneeReplacement: "2L–3L", appendectomy: "60K–90K" },
    description: "Orthopaedic centre of excellence with dedicated spine & sports unit.",
  },
  {
    id: 8,
    name: "NIMHANS (National Institute of Mental Health)",
    lat: 12.9401,
    lng: 77.5954,
    rating: 4.8,
    distance: 4.9,
    ayushmanBharat: true,
    insuranceProviders: ["National Insurance", "New India", "ESI"],
    pricing: { general: 100, semiPrivate: 350, private: 900 },
    emergency: true,
    specialties: ["Psychiatry", "Neurology", "Neurosurgery", "Psychology"],
    departments: ["Psychiatry", "Neurology", "Neurosurgery", "Clinical Psychology", "Neurophysiology"],
    specialists: [
      { name: "Dr. Seema Rao", dept: "Psychiatry", exp: "28 yrs" },
      { name: "Dr. Girish Babu", dept: "Neurosurgery", exp: "24 yrs" },
    ],
    bedAvailability: { general: 200, semiPrivate: 50, private: 20, icu: 15 },
    estimatedTreatmentCost: { bypass: "N/A", kneeReplacement: "N/A", appendectomy: "Free under Ayushman" },
    description: "Premier national institute for neurological and psychiatric disorders.",
  },
  {
    id: 9,
    name: "Aster CMI Hospital",
    lat: 13.0456,
    lng: 77.5918,
    rating: 4.5,
    distance: 13.2,
    ayushmanBharat: false,
    insuranceProviders: ["Star Health", "HDFC ERGO", "Bajaj Allianz", "ICICI Lombard"],
    pricing: { general: 1600, semiPrivate: 3500, private: 7000 },
    emergency: true,
    specialties: ["Cardiology", "Oncology", "Gastroenterology", "Urology"],
    departments: ["Cardiology", "Oncology", "Gastroenterology", "Urology", "Dermatology", "ENT"],
    specialists: [
      { name: "Dr. Sajith Kumar", dept: "Cardiology", exp: "17 yrs" },
      { name: "Dr. Neetha Menon", dept: "Oncology", exp: "13 yrs" },
    ],
    bedAvailability: { general: 38, semiPrivate: 25, private: 16, icu: 11 },
    estimatedTreatmentCost: { bypass: "3L–5L", kneeReplacement: "2L–3.2L", appendectomy: "65K–1L" },
    description: "Modern facility with strong cardiac and cancer care programmes.",
  },
  {
    id: 10,
    name: "M.S. Ramaiah Medical College Hospital",
    lat: 13.0234,
    lng: 77.5598,
    rating: 4.1,
    distance: 10.8,
    ayushmanBharat: true,
    insuranceProviders: ["National Insurance", "New India", "Star Health", "United India"],
    pricing: { general: 600, semiPrivate: 1400, private: 2800 },
    emergency: true,
    specialties: ["General Medicine", "Surgery", "Pediatrics", "Gynecology", "Orthopedics"],
    departments: ["General Medicine", "Surgery", "Pediatrics", "Gynecology", "Orthopedics", "Radiology", "Pathology"],
    specialists: [
      { name: "Dr. Venkatesh N.", dept: "Surgery", exp: "26 yrs" },
      { name: "Dr. Nalini Devi", dept: "Gynecology", exp: "20 yrs" },
      { name: "Dr. Hemant Rao", dept: "Pediatrics", exp: "15 yrs" },
    ],
    bedAvailability: { general: 90, semiPrivate: 35, private: 15, icu: 14 },
    estimatedTreatmentCost: { bypass: "2L–3L", kneeReplacement: "1.4L–2L", appendectomy: "40K–70K" },
    description: "Teaching hospital offering affordable multispecialty care.",
  },
  {
    id: 11,
    name: "Sakra World Hospital",
    lat: 12.9390,
    lng: 77.6894,
    rating: 4.6,
    distance: 7.5,
    ayushmanBharat: false,
    insuranceProviders: ["Star Health", "HDFC ERGO", "Tata AIG", "Bajaj Allianz"],
    pricing: { general: 1700, semiPrivate: 3800, private: 7500 },
    emergency: true,
    specialties: ["Neurology", "Orthopedics", "Gastroenterology", "Robotic Surgery"],
    departments: ["Neurology", "Orthopedics", "Gastroenterology", "Robotic Surgery", "Endocrinology"],
    specialists: [
      { name: "Dr. Raju Vaishya", dept: "Orthopedics", exp: "23 yrs" },
      { name: "Dr. Sita Ganguly", dept: "Neurology", exp: "18 yrs" },
    ],
    bedAvailability: { general: 30, semiPrivate: 20, private: 20, icu: 8 },
    estimatedTreatmentCost: { bypass: "3.5L–5L", kneeReplacement: "2.5L–3.8L", appendectomy: "75K–1.1L" },
    description: "High-tech facility with advanced robotic and minimally invasive surgery.",
  },
  {
    id: 12,
    name: "District Hospital Ramanagara",
    lat: 12.7185,
    lng: 77.2819,
    rating: 3.5,
    distance: 45.0,
    ayushmanBharat: true,
    insuranceProviders: ["National Insurance", "ESI", "New India"],
    pricing: { general: 80, semiPrivate: 250, private: 600 },
    emergency: true,
    specialties: ["General Medicine", "Surgery", "Gynecology"],
    departments: ["General Medicine", "Surgery", "Gynecology", "Pediatrics", "ENT"],
    specialists: [
      { name: "Dr. Mahesh V.", dept: "Surgery", exp: "14 yrs" },
    ],
    bedAvailability: { general: 60, semiPrivate: 10, private: 5, icu: 4 },
    estimatedTreatmentCost: { bypass: "Under PM-JAY", kneeReplacement: "Under PM-JAY", appendectomy: "Free" },
    description: "District-level government hospital serving rural population.",
  },
  {
    id: 13,
    name: "Cloudnine Hospital (Bellandur)",
    lat: 12.9278,
    lng: 77.6691,
    rating: 4.6,
    distance: 6.1,
    ayushmanBharat: false,
    insuranceProviders: ["Star Health", "HDFC ERGO", "ICICI Lombard"],
    pricing: { general: 2200, semiPrivate: 5000, private: 10000 },
    emergency: false,
    specialties: ["Gynecology", "Obstetrics", "Neonatology", "Pediatrics"],
    departments: ["Gynecology", "Obstetrics", "Neonatology", "Pediatrics", "Fertility"],
    specialists: [
      { name: "Dr. Anuradha Prasanna", dept: "Obstetrics", exp: "19 yrs" },
      { name: "Dr. Deepa Bhat", dept: "Neonatology", exp: "13 yrs" },
    ],
    bedAvailability: { general: 10, semiPrivate: 20, private: 30, icu: 8 },
    estimatedTreatmentCost: { bypass: "N/A", kneeReplacement: "N/A", appendectomy: "90K–1.3L" },
    description: "Specialised in women & child health, maternity, and fertility.",
  },
  {
    id: 14,
    name: "Kempegowda Institute of Medical Sciences",
    lat: 12.9411,
    lng: 77.5612,
    rating: 4.0,
    distance: 5.7,
    ayushmanBharat: true,
    insuranceProviders: ["National Insurance", "United India", "New India"],
    pricing: { general: 450, semiPrivate: 1100, private: 2200 },
    emergency: true,
    specialties: ["Cardiology", "General Medicine", "Surgery", "Orthopedics"],
    departments: ["Cardiology", "General Medicine", "Surgery", "Orthopedics", "Gynecology", "ENT", "Ophthalmology"],
    specialists: [
      { name: "Dr. Balakrishna Rao", dept: "Cardiology", exp: "22 yrs" },
      { name: "Dr. Shantha Reddy", dept: "General Medicine", exp: "18 yrs" },
    ],
    bedAvailability: { general: 75, semiPrivate: 25, private: 10, icu: 10 },
    estimatedTreatmentCost: { bypass: "1.5L–2.5L", kneeReplacement: "1.2L–2L", appendectomy: "35K–60K" },
    description: "Government-aided teaching hospital with broad specialty coverage.",
  },
  {
    id: 15,
    name: "St. John's Medical College Hospital",
    lat: 12.9293,
    lng: 77.6247,
    rating: 4.3,
    distance: 3.2,
    ayushmanBharat: true,
    insuranceProviders: ["Star Health", "National Insurance", "New India", "United India"],
    pricing: { general: 700, semiPrivate: 1600, private: 3200 },
    emergency: true,
    specialties: ["Oncology", "Cardiology", "Neurology", "Transplant", "Pediatrics"],
    departments: ["Oncology", "Cardiology", "Neurology", "Transplant", "Pediatrics", "Dermatology", "Rheumatology"],
    specialists: [
      { name: "Dr. Maria Sequeira", dept: "Oncology", exp: "21 yrs" },
      { name: "Dr. Thomas Philip", dept: "Cardiology", exp: "28 yrs" },
      { name: "Dr. Annie Jacob", dept: "Neurology", exp: "15 yrs" },
    ],
    bedAvailability: { general: 100, semiPrivate: 40, private: 20, icu: 16 },
    estimatedTreatmentCost: { bypass: "2L–3.5L", kneeReplacement: "1.5L–2.5L", appendectomy: "50K–80K" },
    description: "Renowned charitable hospital offering quality care at affordable rates.",
  },
];

// Compute recommendation score for each hospital
// Plan formula: score = (1/distance)*0.4 + rating*0.3 + affordability*0.3
// We normalize components to keep scores stable across datasets.
export function computeScores(hospitals, budget = 3000) {
  const maxRating = 5;

  // Distance: higher score for smaller distance. Use 1/(d+eps) then normalize by max.
  const eps = 0.1;
  const invDistances = hospitals.map(h => 1 / (Math.max(h.distance, 0) + eps));
  const maxInvDist = Math.max(...invDistances, 1);

  return hospitals.map((h, idx) => {
    const distanceScore = (1 / (Math.max(h.distance, 0) + eps)) / maxInvDist; // 0..1
    const ratingScore = (h.rating || 0) / maxRating; // 0..1

    // Affordability: 1 if within budget else scaled down, clamped.
    const affordabilityRaw = h.pricing?.general ? (budget / h.pricing.general) : 0;
    const affordabilityScore = Math.max(0, Math.min(1, affordabilityRaw));

    const score = distanceScore * 0.4 + ratingScore * 0.3 + affordabilityScore * 0.3;
    return { ...h, score: parseFloat(score.toFixed(3)) };
  });
}

export const ALL_SPECIALTIES = [
  "Cardiology", "Orthopedics", "Neurology", "Oncology", "General Medicine",
  "Surgery", "Gynecology", "Pediatrics", "Transplant", "Psychiatry",
  "Neurosurgery", "Gastroenterology", "Nephrology", "Urology", "Spine Surgery",
  "Sports Medicine", "Obstetrics", "Neonatology", "Robotic Surgery",
];

export const ALL_INSURANCE = [
  "Star Health", "HDFC ERGO", "National Insurance", "New India",
  "Bajaj Allianz", "ICICI Lombard", "United India", "Tata AIG", "ESI",
];
